CREATE OR REPLACE SEMANTIC VIEW COLD_CHAIN_COMPLIANCE.GOLD.SV_SHIPMENT_COMPLIANCE
    TABLES (
        COMPLIANCE_FACTS AS COLD_CHAIN_COMPLIANCE.GOLD.GOLD_COMPLIANCE_FACTS
    )
    FACTS (
        COMPLIANCE_FACTS.MAX_TEMPERATURE_C AS MAX_TEMPERATURE_C,
        COMPLIANCE_FACTS.MINUTES_ABOVE_THRESHOLD AS MINUTES_ABOVE_THRESHOLD
    )
    DIMENSIONS (
        COMPLIANCE_FACTS.SHIPMENT_ID AS SHIPMENT_ID,
        COMPLIANCE_FACTS.ORDER_ID AS ORDER_ID,
        COMPLIANCE_FACTS.BATCH_ID AS BATCH_ID,
        COMPLIANCE_FACTS.SUPPLIER_LOT_ID AS SUPPLIER_LOT_ID,
        COMPLIANCE_FACTS.CUSTOMER_ID AS CUSTOMER_ID,
        COMPLIANCE_FACTS.ERP_STATUS AS ERP_STATUS,
        COMPLIANCE_FACTS.COMPLIANCE_STATUS AS COMPLIANCE_STATUS,
        COMPLIANCE_FACTS.METRIC_DEFINITION_VERSION AS METRIC_DEFINITION_VERSION,
        COMPLIANCE_FACTS.DECISION_REASON AS DECISION_REASON
    )
    METRICS (
        COMPLIANT_SHIPMENT_COUNT AS COUNT_IF(COMPLIANCE_FACTS.COMPLIANCE_STATUS = 'COMPLIANT')
    );

CREATE OR REPLACE SEMANTIC VIEW COLD_CHAIN_COMPLIANCE.GOLD.SV_SHIPMENT_EVIDENCE
    TABLES (
        COMPLIANCE_FACTS AS COLD_CHAIN_COMPLIANCE.GOLD.GOLD_COMPLIANCE_FACTS
    )
    FACTS (
        COMPLIANCE_FACTS.MAX_TEMPERATURE_C AS MAX_TEMPERATURE_C,
        COMPLIANCE_FACTS.MINUTES_ABOVE_THRESHOLD AS MINUTES_ABOVE_THRESHOLD
    )
    DIMENSIONS (
        COMPLIANCE_FACTS.SHIPMENT_ID AS SHIPMENT_ID,
        COMPLIANCE_FACTS.BATCH_ID AS BATCH_ID,
        COMPLIANCE_FACTS.ERP_STATUS AS ERP_STATUS,
        COMPLIANCE_FACTS.COMPLIANCE_STATUS AS COMPLIANCE_STATUS,
        COMPLIANCE_FACTS.DECISION_REASON AS DECISION_REASON
    );

CREATE OR REPLACE SEMANTIC VIEW COLD_CHAIN_COMPLIANCE.GOLD.SV_COMPLIANCE_AUDIT
    TABLES (
        AUDIT AS COLD_CHAIN_COMPLIANCE.GOVERNANCE.AUDIT_COMPLIANCE_DECISIONS
    )
    DIMENSIONS (
        AUDIT.AUDIT_ID AS AUDIT_ID,
        AUDIT.SHIPMENT_ID AS SHIPMENT_ID,
        AUDIT.COMPLIANCE_STATUS AS COMPLIANCE_STATUS,
        AUDIT.RESOLUTION_ACTION AS RESOLUTION_ACTION,
        AUDIT.METRIC_DEFINITION_VERSION AS METRIC_DEFINITION_VERSION,
        AUDIT.SENSOR_EVIDENCE_REF AS SENSOR_EVIDENCE_REF,
        AUDIT.REGULATORY_EVIDENCE_REF AS REGULATORY_EVIDENCE_REF,
        AUDIT.DECISION_REASON AS DECISION_REASON,
        AUDIT.ACTOR AS ACTOR,
        AUDIT.AUDIT_STATUS AS AUDIT_STATUS
    );

CREATE OR REPLACE SEMANTIC VIEW COLD_CHAIN_COMPLIANCE.GOLD.SV_COLD_CHAIN_ONTOLOGY
    TABLES (
        COLD_CHAIN_COMPLIANCE.BRONZE.SHIPMENTS PRIMARY KEY (SHIPMENT_ID),
        COLD_CHAIN_COMPLIANCE.BRONZE.PART_BATCHES PRIMARY KEY (BATCH_ID),
        COLD_CHAIN_COMPLIANCE.BRONZE.SUPPLIER_LOTS PRIMARY KEY (SUPPLIER_LOT_ID),
        COLD_CHAIN_COMPLIANCE.BRONZE.ORDERS PRIMARY KEY (ORDER_ID),
        COLD_CHAIN_COMPLIANCE.BRONZE.CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
    )
    RELATIONSHIPS (
        SHIPMENTS_TO_CUSTOMER AS SHIPMENTS(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
        SHIPMENTS_TO_ORDER AS SHIPMENTS(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
        SHIPMENTS_TO_BATCH AS SHIPMENTS(BATCH_ID) REFERENCES PART_BATCHES(BATCH_ID),
        SHIPMENTS_TO_LOT AS SHIPMENTS(SUPPLIER_LOT_ID) REFERENCES SUPPLIER_LOTS(SUPPLIER_LOT_ID)
    )
    DIMENSIONS (
        SHIPMENTS.SHIPMENT_ID AS SHIPMENT_ID,
        SHIPMENTS.ERP_STATUS AS ERP_STATUS,
        SHIPMENTS.BATCH_ID AS BATCH_ID,
        PART_BATCHES.PRODUCT_NAME AS PRODUCT_NAME,
        PART_BATCHES.PRODUCT_TYPE AS PRODUCT_TYPE,
        SUPPLIER_LOTS.SUPPLIER_NAME AS SUPPLIER_NAME,
        SUPPLIER_LOTS.CERTIFICATION_STATUS AS CERTIFICATION_STATUS,
        CUSTOMERS.CUSTOMER_NAME AS CUSTOMER_NAME,
        CUSTOMERS.REGION AS REGION
    );

CREATE OR REPLACE SEMANTIC VIEW COLD_CHAIN_COMPLIANCE.GOLD.SV_REGULATORY_EVIDENCE
    TABLES (
        EVIDENCE AS COLD_CHAIN_COMPLIANCE.GOLD.REGULATORY_EVIDENCE PRIMARY KEY (EVIDENCE_ID)
    )
    FACTS (
        EVIDENCE.PAGE_NUMBER AS PAGE_NUMBER
    )
    DIMENSIONS (
        EVIDENCE.EVIDENCE_ID AS EVIDENCE_ID,
        EVIDENCE.SHIPMENT_ID AS SHIPMENT_ID,
        EVIDENCE.DOCUMENT_NAME AS DOCUMENT_NAME,
        EVIDENCE.CLAUSE_REFERENCE AS CLAUSE_REFERENCE,
        EVIDENCE.EVIDENCE_TEXT AS EVIDENCE_TEXT,
        EVIDENCE.SOURCE_TYPE AS SOURCE_TYPE
    );
```

---

## 5. Cortex Search Service and Supporting Objects

The Cortex Search service indexes `COMPLIANCE_DOCUMENT_CHUNKS` (defined in section 3).

```sql
CREATE OR REPLACE CORTEX SEARCH SERVICE COLD_CHAIN_COMPLIANCE.GOLD.COMPLIANCE_EVIDENCE_SEARCH
    ON EVIDENCE_TEXT
    ATTRIBUTES SHIPMENT_ID, DOCUMENT_NAME, CLAUSE_REFERENCE, PAGE_NUMBER, SOURCE_TYPE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
    AS (
        SELECT
            EVIDENCE_ID,
            SHIPMENT_ID,
            DOCUMENT_NAME,
            CLAUSE_REFERENCE,
            PAGE_NUMBER,
            EVIDENCE_TEXT,
            SOURCE_TYPE
        FROM COLD_CHAIN_COMPLIANCE.GOLD.COMPLIANCE_DOCUMENT_CHUNKS
    );
```

---

## 6. Cortex Agent / Configuration Objects

No Cortex Agents or Streamlit apps deployed in this database.

---

## 7. GOVERNANCE Objects

### 7a. Tables

```sql
CREATE OR REPLACE TABLE COLD_CHAIN_COMPLIANCE.GOVERNANCE.AUDIT_COMPLIANCE_DECISIONS (
