CREATE OR REPLACE CORTEX SEARCH SERVICE COLD_CHAIN_COMPLIANCE.GOLD.COMPLIANCE_EVIDENCE_SEARCH
    ON EVIDENCE_TEXT
    ATTRIBUTES SHIPMENT_ID, DOCUMENT_NAME, CLAUSE_REFERENCE, PAGE_NUMBER, SOURCE_TYPE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
    AS (
        SELECT
            EVIDENCE_ID,
            SHIPMENT_ID,
            DOCUMENT_NAME,
            CLAUSE_REFERENCE,
            PAGE_NUMBER,
            EVIDENCE_TEXT,
            SOURCE_TYPE
        FROM COLD_CHAIN_COMPLIANCE.GOLD.COMPLIANCE_DOCUMENT_CHUNKS
    );
