CREATE OR REPLACE TABLE COLD_CHAIN_COMPLIANCE.GOVERNANCE.AUDIT_COMPLIANCE_DECISIONS (
    AUDIT_ID VARCHAR(16777216),
    SHIPMENT_ID VARCHAR(16777216),
    COMPLIANCE_STATUS VARCHAR(16777216),
    RESOLUTION_ACTION VARCHAR(16777216),
    METRIC_DEFINITION_VERSION VARCHAR(16777216),
    SENSOR_EVIDENCE_REF VARCHAR(16777216),
    REGULATORY_EVIDENCE_REF VARCHAR(16777216),
    DECISION_REASON VARCHAR(16777216),
    ACTOR VARCHAR(16777216),
    DECIDED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    AUDIT_STATUS VARCHAR(16777216)
);

CREATE OR REPLACE TABLE COLD_CHAIN_COMPLIANCE.GOVERNANCE.LEGACY_COMPLIANCE_DEFINITIONS (
    DEFINITION_ID VARCHAR(16777216),
    SOURCE_SYSTEM VARCHAR(16777216),
    DEFINITION_NAME VARCHAR(16777216),
    COMPLIANCE_RULE VARCHAR(16777216),
    SHIPMENT_STATUS_FOR_SH_101 VARCHAR(16777216),
    NOTES VARCHAR(16777216)
);


CREATE OR REPLACE TAG COLD_CHAIN_COMPLIANCE.GOVERNANCE.DATA_SENSITIVITY;


CREATE OR REPLACE MASKING POLICY COLD_CHAIN_COMPLIANCE.GOVERNANCE.MASK_RAW_TEMPERATURE
    AS (VAL NUMBER(5,2))
    RETURNS NUMBER(5,2) ->
    CASE
        WHEN CURRENT_ROLE() = 'COLD_CHAIN_QUALITY' THEN VAL
        ELSE NULL
    END;


ALTER TAG COLD_CHAIN_COMPLIANCE.GOVERNANCE.DATA_SENSITIVITY
    SET MASKING POLICY COLD_CHAIN_COMPLIANCE.GOVERNANCE.MASK_RAW_TEMPERATURE;

ALTER TABLE COLD_CHAIN_COMPLIANCE.BRONZE.IOT_TEMP_LOGS
    MODIFY COLUMN TEMPERATURE_C
    SET TAG COLD_CHAIN_COMPLIANCE.GOVERNANCE.DATA_SENSITIVITY = 'RAW_TEMPERATURE';


CREATE OR REPLACE STREAM COLD_CHAIN_COMPLIANCE.GOVERNANCE.IOT_TEMP_LOGS_STREAM
    ON TABLE COLD_CHAIN_COMPLIANCE.BRONZE.IOT_TEMP_LOGS
    APPEND_ONLY = TRUE;


CREATE OR REPLACE TASK COLD_CHAIN_COMPLIANCE.GOVERNANCE.TASK_DETECT_COLD_CHAIN_BREACHES
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('COLD_CHAIN_COMPLIANCE.GOVERNANCE.IOT_TEMP_LOGS_STREAM')
AS
INSERT INTO COLD_CHAIN_COMPLIANCE.GOLD.GOLD_COMPLIANCE_BREACHES
(
    BREACH_ID, SHIPMENT_ID, SENSOR_ID, EVENT_ID, EVENT_TS,
    TEMPERATURE_C, THRESHOLD_C, BREACH_TYPE, STATUS
)
SELECT
    'BREACH-' || EVENT_ID,
    SHIPMENT_ID, SENSOR_ID, EVENT_ID, EVENT_TS,
    TEMPERATURE_C, 8.00, 'TEMPERATURE_ABOVE_THRESHOLD', 'OPEN'
FROM COLD_CHAIN_COMPLIANCE.GOVERNANCE.IOT_TEMP_LOGS_STREAM
WHERE METADATA$ACTION = 'INSERT'
  AND TEMPERATURE_C > 8;


CREATE ROLE IF NOT EXISTS COLD_CHAIN_QUALITY;
CREATE ROLE IF NOT EXISTS COLD_CHAIN_LOGISTICS;
CREATE ROLE IF NOT EXISTS COLD_CHAIN_AUDIT_WRITER;


-- COLD_CHAIN_QUALITY
GRANT USAGE ON DATABASE COLD_CHAIN_COMPLIANCE TO ROLE COLD_CHAIN_QUALITY;
GRANT USAGE ON SCHEMA COLD_CHAIN_COMPLIANCE.BRONZE TO ROLE COLD_CHAIN_QUALITY;
GRANT USAGE ON SCHEMA COLD_CHAIN_COMPLIANCE.GOLD TO ROLE COLD_CHAIN_QUALITY;
GRANT USAGE ON SCHEMA COLD_CHAIN_COMPLIANCE.GOVERNANCE TO ROLE COLD_CHAIN_QUALITY;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE COLD_CHAIN_QUALITY;
GRANT SELECT ON TABLE COLD_CHAIN_COMPLIANCE.BRONZE.IOT_TEMP_LOGS TO ROLE COLD_CHAIN_QUALITY;
GRANT SELECT, INSERT ON TABLE COLD_CHAIN_COMPLIANCE.GOLD.GOLD_COMPLIANCE_BREACHES TO ROLE COLD_CHAIN_QUALITY;
GRANT SELECT ON STREAM COLD_CHAIN_COMPLIANCE.GOVERNANCE.IOT_TEMP_LOGS_STREAM TO ROLE COLD_CHAIN_QUALITY;
GRANT CREATE TASK ON SCHEMA COLD_CHAIN_COMPLIANCE.GOVERNANCE TO ROLE COLD_CHAIN_QUALITY;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE COLD_CHAIN_QUALITY;

-- VW_QUALITY_SENSOR_EVIDENCE ownership
GRANT OWNERSHIP ON VIEW COLD_CHAIN_COMPLIANCE.GOLD.VW_QUALITY_SENSOR_EVIDENCE
    TO ROLE COLD_CHAIN_QUALITY COPY CURRENT GRANTS;

-- Task ownership
GRANT OWNERSHIP ON TASK COLD_CHAIN_COMPLIANCE.GOVERNANCE.TASK_DETECT_COLD_CHAIN_BREACHES
    TO ROLE COLD_CHAIN_QUALITY COPY CURRENT GRANTS;

-- COLD_CHAIN_LOGISTICS
GRANT USAGE ON DATABASE COLD_CHAIN_COMPLIANCE TO ROLE COLD_CHAIN_LOGISTICS;
GRANT USAGE ON SCHEMA COLD_CHAIN_COMPLIANCE.GOLD TO ROLE COLD_CHAIN_LOGISTICS;
GRANT SELECT ON VIEW COLD_CHAIN_COMPLIANCE.GOLD.VW_LOGISTICS_COMPLIANCE TO ROLE COLD_CHAIN_LOGISTICS;

-- COLD_CHAIN_AUDIT_WRITER
GRANT USAGE ON DATABASE COLD_CHAIN_COMPLIANCE TO ROLE COLD_CHAIN_AUDIT_WRITER;
GRANT USAGE ON SCHEMA COLD_CHAIN_COMPLIANCE.GOVERNANCE TO ROLE COLD_CHAIN_AUDIT_WRITER;
GRANT SELECT, INSERT ON TABLE COLD_CHAIN_COMPLIANCE.GOVERNANCE.AUDIT_COMPLIANCE_DECISIONS TO ROLE COLD_CHAIN_AUDIT_WRITER;

-- Semantic View grants
GRANT SELECT ON SEMANTIC VIEW COLD_CHAIN_COMPLIANCE.GOLD.SV_SHIPMENT_COMPLIANCE TO ROLE ACCOUNTADMIN;

-- Database role grants
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_ANALYST_USER TO ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.COPILOT_USER TO ROLE ACCOUNTADMIN;

-- Grant the project roles to your deployment user separately.
-- GRANT ROLE COLD_CHAIN_QUALITY TO USER <your_username>;
-- GRANT ROLE COLD_CHAIN_LOGISTICS TO USER <your_username>;
-- GRANT ROLE COLD_CHAIN_AUDIT_WRITER TO USER <your_username>;

ALTER TASK COLD_CHAIN_COMPLIANCE.GOVERNANCE.TASK_DETECT_COLD_CHAIN_BREACHES RESUME;
